import { useState, type FormEvent } from 'react';
import type { NovaTarefa, Prioridade, Tarefa } from '../types/Tarefa';
import { hojeLocal } from '../utils/tarefas';
import { useTarefas } from '../context/TarefasContext';
export function TaskForm({tarefa,cancelar,sucesso}:{tarefa?:Tarefa;cancelar:()=>void;sucesso:()=>void}){
 const {salvar,ocupada,tarefas}=useTarefas();const [titulo,setTitulo]=useState(tarefa?.titulo||''),[descricao,setDescricao]=useState(tarefa?.descricao||''),[data,setData]=useState(tarefa?.data||hojeLocal()),[prioridade,setPrioridade]=useState<Prioridade>(tarefa?.prioridade||'medium'),[projeto,setProjeto]=useState(tarefa?.projeto||''),[erro,setErro]=useState('');
 async function enviar(e:FormEvent){e.preventDefault();if(!titulo.trim()){setErro('Informe o título da tarefa.');return;}setErro('');const dados:NovaTarefa={titulo:titulo.trim(),descricao:descricao.trim(),data,prioridade,projeto:projeto.trim(),concluida:tarefa?.concluida||false};try{await salvar(dados,tarefa?._id);sucesso();}catch{setErro('Não foi possível salvar. Confira a mensagem de erro na página e tente novamente.');}}
 return <form onSubmit={enviar}><fieldset disabled={ocupada}><label>Título<input autoFocus required maxLength={120} value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="O que você precisa fazer?"/></label><label>Descrição<textarea rows={3} maxLength={2000} value={descricao} onChange={e=>setDescricao(e.target.value)} placeholder="Acrescente os detalhes da tarefa"/></label><div className="form-row"><label>Prazo<input type="date" required value={data} onChange={e=>setData(e.target.value)}/></label><label>Prioridade<select value={prioridade} onChange={e=>setPrioridade(e.target.value as Prioridade)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label></div><label>Projeto<input list="projetos" maxLength={80} value={projeto} onChange={e=>setProjeto(e.target.value)} placeholder="Ex.: TaskFlow"/></label><datalist id="projetos">{[...new Set(tarefas.map(t=>t.projeto))].map(p=><option key={p} value={p}/>)}</datalist>{erro&&<p role="alert" className="error">{erro}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={cancelar}>Cancelar</button><button className="primary" type="submit">{ocupada?'Salvando...':'Salvar tarefa'}</button></div></fieldset></form>;
}
